server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commentaires?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
