server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/produits?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
